version: '3'
services:
  app:
    build:
      #同じ階層のDockerfileを指定
      context: .
    volumes:
      #ホストとコンテナを同期
      - .:/app
      #コンテナ外部のボリュームとコンテナを同期
      - node_modules:/app/node_modules
    ports:
      #ホストとコンテナのポート3000を同期（Next.js用）
      - 3000:3000
      #ホストとコンテナのポート6006を同期（Storybook用）
      - 6006:6006
volumes:
  #名前付きボリュームをコンテナの外部に作成
  node_modules: